"""
ReportLab PDF report generator for CURRENCYGuard.
Generates downloadable authenticity reports.
"""

import io
import logging
from datetime import datetime
from typing import List, Dict
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)

logger = logging.getLogger(__name__)

VERDICT_COLORS = {
    "GENUINE": colors.HexColor("#28a745"),
    "SUSPECT": colors.HexColor("#ffc107"),
    "COUNTERFEIT": colors.HexColor("#dc3545"),
    "INCONCLUSIVE": colors.HexColor("#6c757d"),
}


def generate_currency_report(
    analysis_id: str,
    denomination: str,
    verdict: str,
    confidence: float,
    feature_checks: List[Dict],
    ai_reasoning: str,
) -> bytes:
    """Generate PDF authenticity report. Returns bytes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm,
    )

    styles = getSampleStyleSheet()
    elements = []

    title_style = ParagraphStyle(
        "Title",
        parent=styles["Heading1"],
        fontSize=20,
        spaceAfter=6,
        textColor=colors.HexColor("#1a1a2e"),
    )
    elements.append(Paragraph("SENTINEL CURRENCYGuard", title_style))
    elements.append(Paragraph("Currency Authenticity Report", styles["Heading2"]))
    elements.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1a1a2e")))
    elements.append(Spacer(1, 0.3*cm))

    meta_data = [
        ["Analysis ID", analysis_id],
        ["Generated", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        ["Denomination", f"Rs.{denomination}"],
        ["Overall Confidence", f"{confidence:.1%}"],
    ]
    meta_table = Table(meta_data, colWidths=[5*cm, 11*cm])
    meta_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#f8f9fa"), colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dee2e6")),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 0.5*cm))

    verdict_color = VERDICT_COLORS.get(verdict, colors.gray)
    verdict_data = [[f"VERDICT: {verdict}"]]
    verdict_table = Table(verdict_data, colWidths=[16*cm])
    verdict_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 16),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
        ("BACKGROUND", (0, 0), (-1, -1), verdict_color),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("PADDING", (0, 0), (-1, -1), 12),
        ("ROUNDEDCORNERS", [6, 6, 6, 6]),
    ]))
    elements.append(verdict_table)
    elements.append(Spacer(1, 0.5*cm))

    elements.append(Paragraph("Security Feature Analysis", styles["Heading2"]))
    check_header = [["Feature", "Result", "Confidence", "Details"]]
    check_rows = []
    for check in feature_checks:
        result = "PASS" if check["passed"] else "FAIL"
        check_rows.append([
            check["feature_name"],
            result,
            f"{check['confidence']:.1%}",
            check["details"][:80] + "..." if len(check["details"]) > 80 else check["details"]
        ])

    check_table = Table(
        check_header + check_rows,
        colWidths=[3.5*cm, 2*cm, 2.5*cm, 8*cm]
    )
    check_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dee2e6")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8f9fa")]),
        ("PADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    elements.append(check_table)
    elements.append(Spacer(1, 0.5*cm))

    elements.append(Paragraph("AI Reasoning", styles["Heading2"]))
    elements.append(Paragraph(ai_reasoning, styles["Normal"]))
    elements.append(Spacer(1, 0.5*cm))

    elements.append(HRFlowable(width="100%", thickness=1, color=colors.gray))
    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.gray,
    )
    elements.append(Paragraph(
        "DISCLAIMER: This report is generated by an AI system for preliminary screening purposes only. "
        "It does not constitute legal evidence. Final determination must be made by authorized RBI officials "
        "or certified currency verification equipment. SENTINEL - ET AI Hackathon 2.0.",
        disclaimer_style
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer.getvalue()
